In [2]:
# =========================================
# 1. Imports
# =========================================
import pandas as pd
from ydata_profiling import ProfileReport
import argparse
import os
import sys

c:\Users\jmart\Documents\05_Studium\04_Programmierprojekte\04_Semester\DigitalStorytellingAndVisualisation\visualisierungsprojekt\PODSV_Visualisierungsprojekt\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
# =========================================
# 2. CSV-Datei einlesen
# =========================================

df = pd.read_csv(
    r"..\data\2634_Selects2023_PES_Data_v2.0.csv",
    sep=";"
)

# erste Kontrolle
print("Shape:", df.shape)
df.head()

Shape: (5033, 308)

C:\Users\jmart\AppData\Local\Temp\ipykernel_32412\2677121.py:5: DtypeWarning: Columns (206,207,208,209,210,211,212,213,214,215) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,userid,langint,imode,indate_paper,language_paper,intstart,intend,Finished,Completion_Rate,totaltime,...,weight_tot,weight_t_zh,weight_p_zh,weight_tot_zh,weight_t_ti,weight_p_ti,weight_tot_ti,weight_t_ge,weight_p_ge,weight_tot_ge
0,1001,2,1,,,11/7/2023 14:28:40,11/16/2023 21:19:15,1,2,"13370,5666666667",...,",599246512333914",1,1,1,1,1,1,"1,49920369",1,"1,49920369"
1,1002,1,1,,,10/24/2023 13:26:04,10/24/2023 13:51:42,1,2,"25,6333333333333",...,",976448777640773",1,1,1,1,1,1,1,1,1
2,1003,1,1,,,11/13/2023 20:36:39,11/13/2023 20:56:14,1,2,"19,5666666666667",...,"1,18620046322414",1,1,1,1,1,1,1,1,1
3,1004,1,1,,,10/24/2023 7:41:41,10/24/2023 8:13:56,1,2,"32,2333333333333",...,",552334100995496",1,1,1,1,1,1,1,1,1
4,1005,1,1,,,11/3/2023 13:42:10,11/3/2023 14:05:17,1,2,"23,1166666666667",...,",188235121344307",1,1,1,1,1,1,1,1,1

In [13]:
df.describe()

,userid,langint,imode,sex,birthyear,age,agecat,f10000,f10100,f12700c,...,f15815,f28910,f29100,f21200,birthcountry_sample,hhsize_sample,bigregion_sample,smt3,smt9,msize
count,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,...,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000,5033.000000
mean,3517.000000,1.519173,1.103517,1.359626,1962.087224,51.204451,3.765349,14.090602,2.418637,26.108881,...,1.413074,2.092589,0.656070,-0.402742,8127.603219,2.677330,3.763362,1.518975,16.979336,4.550964
std,1453.046283,0.714432,0.304663,4.035787,137.755901,20.531204,7.040930,8.787329,5.414550,45.130438,...,12.793084,25.392487,18.347596,13.904274,76.282585,1.306854,2.111798,0.746273,7.551991,1.867063
min,1001.000000,1.000000,1.000000,-99.000000,-99.000000,-99.000000,-99.000000,1.000000,-99.000000,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,8100.000000,1.000000,1.000000,1.000000,11.000000,1.000000
25%,2259.000000,1.000000,1.000000,1.000000,1957.000000,37.000000,3.000000,5.000000,2.000000,6.000000,...,2.000000,4.000000,1.000000,1.000000,8100.000000,2.000000,2.000000,1.000000,11.000000,3.000000
50%,3517.000000,1.000000,1.000000,2.000000,1969.000000,53.000000,4.000000,17.000000,3.000000,17.000000,...,3.000000,7.000000,1.000000,2.000000,8100.000000,2.000000,4.000000,1.000000,12.000000,5.000000
75%,4775.000000,2.000000,1.000000,2.000000,1986.000000,66.000000,6.000000,21.000000,3.000000,53.000000,...,4.000000,10.000000,2.000000,2.000000,8100.000000,4.000000,6.000000,2.000000,22.000000,6.000000
max,6033.000000,3.000000,2.000000,2.000000,2005.000000,102.000000,7.000000,26.000000,4.000000,207.000000,...,4.000000,20.000000,98.000000,3.000000,8601.000000,9.000000,7.000000,3.000000,33.000000,8.000000

In [12]:
df.describe()

dfnoNAn = df.dropna()

dfnoNAn['age'].where(dfnoNAn['age'] < 18).bin([0, 18, 100], labels=['<18', '18-100'], inplace=True)

AttributeError: 'Series' object has no attribute 'bin'